    <div id="sidebar1">
    
   <div class="sidebar1_contents">
        <h2>Get Started with..</h2>
        <ul>             
            <?php if( App_Auth::getUserRole() == USER_ADMIN  ||  App_Auth::getUserRole() == USER_CLIENT ) : ?>
                <li><a href="/client">Client's Panel</a></li>                 
            <?php endif;?>
                
            <?php if( App_Auth::getUserRole() == USER_ADMIN  ||  App_Auth::getUserRole() == USER_LAWYER ) : ?>
                <li><a href="/lawyer">Lawyer's Panel</a></li>                           
            <?php endif;?>
                
            <?php if( App_Auth::getUserRole() == USER_ADMIN  ||  App_Auth::getUserRole() == USER_ACCOUNTANT ) : ?>
                <li><a href="#">Account Details</a></li>                        
            <?php endif;?>
                        
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Details</a></li>
        </ul>
        <!-- / .sidebar1_contents -->
    </div>
    <div class="sidebar1_box">
        <?php if (empty($this->loggedIdUserId)) {?>
            <?php echo $this->loginForm; ?>	<br/> 
            <!-- <a href="/index/register"><i>Register here</i></a> -->   
        <?php } else { ?>
            <p> Welcome, <?php echo $this->loggedInUser; ?> </p>
        <?php } ?>
     </div>
         
</div>
<br />
<div id="mainContent"><img src="images/image.jpg" alt="image1" width="123" height="87" class="fltlft" />
    <p>Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia.	Proin gravida orci porttitor enim accumsan lacinia.</p>
    <br />
    <h2>Law Group, LLC</h2>
    <blockquote>
        <p>&#8220; Lorem Ipsum is simply dummy text of the printing and typesetting industry. &#8221;</p>
        <p class="align-right"> - Law Group, LLC </p>
    </blockquote>
    <p>Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia.	Proin gravida orci porttitor enim accumsan lacinia.</p>
    <br />
    <br />
    <!-- / #mainContent -->
</div>
<br class="clearfloat"/>
