<div id="sidebar1">
    <div class="sidebar1_contents">
        <h2>Practice Areas</h2>
        <ul>
            <li><a href="#">Aliquam liberonare</a></li>
            <li><a href="#">Consectetuer adipiscing</a></li>
            <li><a href="#">Metusin	pellentesque</a></li>
            <li><a href="#">Suspendisse	maurisres</a></li>
            <li><a href="#">Urnanet	molestie semper</a></li>
            <li><a href="#">Proin gravida	porttitor</a></li>
        </ul>
        <!-- / .sidebar1_contents -->
    </div>
    
    <?php if (empty($this->loggedIdUserId)) {?>
    <div class="sidebar1_box">
        <?php echo $this->loginForm; ?>	<br/> 
        <!-- <a href="/index/register"><i>Register here</i></a> -->
    </div>
    <?php } ?>
    
</div>
<br />
<div id="mainContent"><img src="images/image.jpg" alt="image1" width="123" height="87" class="fltlft" />
    <p>Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia.	Proin gravida orci porttitor enim accumsan lacinia.</p>
    <br />
    <h2>Law Group, LLC</h2>
    <blockquote>
        <p>&#8220; Lorem Ipsum is simply dummy text of the printing and typesetting industry. &#8221;</p>
        <p class="align-right"> - Law Group, LLC </p>
    </blockquote>
    <p>Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Proin gravida orci porttitor enim accumsan lacinia.	Proin gravida orci porttitor enim accumsan lacinia.</p>
    <br />
    <br />
    <!-- / #mainContent -->
</div>
<br class="clearfloat"/>
