<div id="content">     
    
<script type="text/javascript">
    	$(function(){
    		$('legend').click(function(){
                        //$(this).parent().find('.lawyer-form').show();
    			$(this).parent().find('.lawyer-form').slideToggle();
    		});
    	});
                
</script>
<div id="dataTable">
  	<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" id="example" width="100%">
		<thead>
			<tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile No</th>
                            <th>Address</th>    
                            <th></th>    
                        </tr>
                </thead>
                <tbody>
                    <?php foreach( $this->lawyerList as $lawyer ) { ?>
                        <tr> 
                            <td><a href="javascript:void()" class ="view-lawyer" id="view_lawyer_<?php echo $lawyer['id']?>"><?php echo $lawyer['name'];?></a></td>
                            <td><?php echo $lawyer['email'];?></td>
                            <td><?php echo $lawyer['mobile_number'];?> <?php if(  $lawyer['home_phone'] ) { echo  '/'.$lawyer['home_phone'] ;}?> </td>
                            <td><?php echo $lawyer['street_line'];?>,<?php echo $lawyer['city'];?></td>
                            <td><a title="Edit Lawyer" href="/lawyer/edit-lawyer/id/<?php echo $lawyer['id'] ?>">Edit </a>|
                                <a id="delete_lawyer_<?php echo $lawyer['id'];?>" title="Delete Lawyer"  href= "javascript:void(0);"> Delete </a>| 
                                <a href="/lawyer/view-lawyer-case/id/<?php echo $lawyer['id'] ?>">View Case</a> </td> 
                        </tr>
                    <?php } ?>
                         
                </tbody>
           </table>                                 
</div>
<br/><br/>
<fieldset>
    <legend>Add Lawyer</legend>    
    <div class="lawyer-form">       
    	<?php echo $this->registerForm; ?>  
    </div>
</fieldset>
<br/>
<!--
<fieldset>
    <legend>Search Lawyer</legend>    
    <div class="lawyer-form">
    	<?php //echo $this->searchForm; ?>  
    </div>
</fieldset>-->
<div><input type="hidden" id="role_type" value="2"></div>
<div> 
<!--<table id="search-table" class="display" cellpadding="0" cellspacing="0" border="0" width="100%"> 
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile No</th>
        <th>Address</th>    
        <th></th> 
    </tr>
    </thead>
    <tbody>       
        <tr id="no-record-tr"><td>No Records <td></tr>
    </tbody>
</table>-->
</div>

</div>


<div id="dialog-form-lawyer" title="Lawyer Details" style="display: none;"></div>