<?php echo $this->doctype() ?><?php 
$action     = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Lawyer Client Management</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  
  <link rel="stylesheet" href="/css/style.css">  
  <link rel="stylesheet" href="/css/library/jquery.alerts.css">  
  <link rel="stylesheet" href="/css/library/jquery_ui_1.10.3.css">  
 
  <script src="/js/library/jquery_1.9.1.js" type="text/javascript"></script>    
  <script src="/js/library/jquery_ui_1.10.3.js" type="text/javascript"></script>
  
  <script src="/js/library/jquery.dataTables.js" type="text/javascript"></script>
  <script src="/js/library/jquery.alerts.js" type="text/javascript"></script>
  <script src="/js/comman.js" type="text/javascript"></script>
  
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php echo $this->headScript() ?> 
    
</head>
<body>
<body class="LegalTemplate">
<div id="container">
<div id="header"> 
	<div id="menu">         
            <ul>
              <li><a href="/" <?php if($controller == 'index'){?> class="current" <?php } else { ?> class="" <?php }?> >Home</a></li>			
              <?php if (App_Auth::isLogged() && App_Auth::getUserRole() == USER_ADMIN ) { ?>              
	              <li><a href="/lawyer/" <?php if($controller == 'lawyer'){?> class="current" <?php } else { ?> class="" <?php }?> >Lawyer's Panel</a></li> 
	              <li><a href="/client/" <?php if($controller == 'client'){?> class="current" <?php } else { ?> class="" <?php }?> >Client's Panel</a></li> 
	              <li><a href="/case/" <?php if($controller == 'case'){?> class="current" <?php } else { ?> class="" <?php }?> >Case's Panels</a></li>
	              <li><a href="/account/" <?php if($controller == 'account'){?> class="current" <?php } else { ?> class="" <?php }?> >Account's Panels</a></li> 
	              <li><a href="/contact/" <?php if($controller == 'contact'){?> class="current" <?php } else { ?> class="" <?php }?> >Contact Us</a></li>                                                         
	              <li><a href ="/auth/logout">Log Out</a></li>
                      
              <?php } elseif( App_Auth::isLogged() && App_Auth::getUserRole() == USER_LAWYER ) { ?>                  
                      <li><a href="/lawyer/" <?php if($controller == 'lawyer'){?> class="current" <?php } else { ?> class="" <?php }?> >Lawyer's Panel</a></li>                   
                      <li><a href="/contact/" <?php if($controller == 'contact'){?> class="current" <?php } else { ?> class="" <?php }?> >Contact Us</a></li>                                                         
	              <li><a href ="/auth/logout">Log Out</a></li>
                      
              <?php } elseif( App_Auth::isLogged() && App_Auth::getUserRole() == USER_CLIENT ) { ?>
                       <li><a href="/client/" <?php if($controller == 'client'){?> class="current" <?php } else { ?> class="" <?php }?> >Client's Panel</a></li> 
                       <li><a href="/contact/" <?php if($controller == 'contact'){?> class="current" <?php } else { ?> class="" <?php }?> >Contact Us</a></li>                                                         
	               <li><a href ="/auth/logout">Log Out</a></li>              
                       
              <?php } elseif( App_Auth::isLogged() && App_Auth::getUserRole() == USER_ACCOUNTANT ) { ?> 
                      <li><a href="/account/" <?php if($controller == 'account'){?> class="current" <?php } else { ?> class="" <?php }?> >Account's Panels</a></li> 
                      <li><a href="/contact/" <?php if($controller == 'contact'){?> class="current" <?php } else { ?> class="" <?php }?> >Contact Us</a></li>                                                         
	              <li><a href ="/auth/logout">Log Out</a></li>
                  
              <?php }                                          
              elseif( 'index' != $controller ){
              	header('Location: ' . $this->baseUrl() );
			  	exit;
              }?>
	   </ul>
	</div><div class="inner_copy"></div>
       <?php  if($controller == 'index' && $action == 'index' ) :?>
            <div class="banner"></div>
       <?php else : ?>        
            <div class="banner-strip"></div>   
       <?php endif;?> 
                              
        <div id="wrapper">            
            <?php if ($this->success) { ?>
                     <div class="success_message"><?php echo $this->success ;?></div>
                     <div style="clear:both"></div>
            <?php } ?>

             <?php if ($this->error) { ?>
                     <div class="success_message"><?php echo $this->error ;?></div>
                     <div style="clear:both"></div>
            <?php } ?>         
            
            <?php echo $this->layout()->content ?>
        </div>          
        
	<div id="footer">
			<center>
				<div class="fleft">Copyright Statement</div>				
			</center>
		<!-- / #footer -->
	</div>
	<!-- / #container -->
</div>
</body>
    
</html>
