<?php echo $this->doctype() ?>
<?php 
$action     = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Lawyer Client Management</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="/css/style.css">  
  <link rel="stylesheet" href="/css/library/jquery.alerts.css">  
 
  <script src="/js/library/jquery.js" type="text/javascript"></script>    
  <script src="/js/library/jquery-ui.min.js" type="text/javascript"></script>
  <script src="/js/library/jquery.dataTables.js" type="text/javascript"></script>
  <script src="/js/library/jquery.alerts.js" type="text/javascript"></script>
  <script src="/js/comman.js" type="text/javascript"></script>
  
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php echo $this->headScript() ?> 
    
</head>
<body>
<body class="LegalTemplate">
<div id="container">
<div id="header">
	<div id="menu">         
            <ul>
              <li><a href="/" <?php if($controller == 'index'){?> class="current" <?php } else { ?> class="" <?php }?> >Home</a></li>			
              <li><a href="/lawyer/" <?php if($controller == 'lawyer'){?> class="current" <?php } else { ?> class="" <?php }?> >Lawyer's Panel</a></li> 
              <li><a href="/client/" <?php if($controller == 'client'){?> class="current" <?php } else { ?> class="" <?php }?> >Client</a></li> 
              <li><a href="/case/" <?php if($controller == 'case'){?> class="current" <?php } else { ?> class="" <?php }?> >Cases</a></li> 
              <li><a href="/account/" <?php if($controller == 'account'){?> class="current" <?php } else { ?> class="" <?php }?> >Account's Panels</a></li> 
              <li><a href="/contact/" <?php if($controller == 'contact'){?> class="current" <?php } else { ?> class="" <?php }?> >Contact Us</a></li>              
	   </ul>
	</div><div class="inner_copy"></div>
       <?php  if($controller == 'index' && $action == 'index' ) :?>
            <div class="banner"></div>
       <?php endif;?> 
            
        <div id="wrapper">            
            <?php echo $this->layout()->content ?>
        </div>          
        
	<div id="footer">
			<center>
				<div class="fleft">Copyright Statement</div>				
			</center>
		<!-- / #footer -->
	</div>
	<!-- / #container -->
</div>
</body>
    
</html>
