<br/>
<?php if( !empty($this->data['users']) ) :?>
<table id="client-details-table">    
    <tbody>
        <tr><th colspan="2" style="text-align:left">Personal Info</th></tr>
        <tr><th>Name</th> <td> <?php echo $this->data['users']['name']; ?> </td></tr>
        <tr><th>Email</th> <td> <?php echo $this->data['users']['email']; ?> </td></tr>
        <tr><th>Contact Person</th> <td> <?php echo $this->data['users']['contact_person']; ?> </td></tr>        
        <tr><th>Contact Number</th> <td> <?php echo $this->data['users']['mobile_number']; ?>,<?php echo $this->data['users']['home_phone']; ?> </td></tr>
        <tr><th>Address</th> <td><?php echo $this->data['users']['street_line']; ?>,<?php echo $this->data['users']['city']; ?></td></tr>
        
        <tr><th colspan="2" style="text-align:left">Bank Details</th></tr>
        <tr><th>Name of the Bank</th> <td><?php echo $this->data['users']['bank_name']; ?></td></tr>
        <tr><th>Account Number</th> <td><?php echo $this->data['users']['bank_account_number']; ?></td></tr> 
        <tr><th>IFSC Code</th> <td><?php echo $this->data['users']['IFSC_code']; ?></td></tr> 
        <tr><th>Pan Number</th> <td><?php echo $this->data['users']['pan_card_number']; ?></td></tr> 
    </tbody>
</table>  
<?php endif ;?>
<br/>

<?php if( !empty($this->data['cases']) ) :?>
<h3> Case Status </h3>
<?php foreach( $this->data['cases'] as $case ) {  $i = 1;?>
    <table id="client-details-table">
    <tbody>
        <tr><th colspan="2" style="text-align:left">Case #<?php echo $i;?></th></tr>
        <tr><th>Assigned lawyer</th> <td> <?php echo App_User::getUserName($case['lawyer_id']); ?> </td></tr>
        <tr><th>Judge lawyer</th> <td> <?php echo $case['judge_name'] ; ?> </td></tr>
        <tr><th>Case Status</th> <td> <?php echo App_User::getStatus( $case['status'] ); ?> </td></tr>
        <tr><th>Allotment Date</th> <td> <?php echo $case['date_of_allotment']; ?> </td></tr>
        <tr><th>Hearing Date</th> <td> <?php echo $case['hearing_date']; ?> </td></tr>
        <tr><th>Next Hearing Date</th> <td> <?php echo $case['next_hearing_date']; ?> </td></tr>
        <tr><th colspan="2" style="text-align:left">Transaction Details</th></tr>
        <tr><th>Transaction Details</th> <td> <?php echo $case['transaction_details']; ?> </td></tr>
        <tr><th>Transaction Type</th> <td> <?php echo $case['transaction_type_id']; ?> </td></tr>
        <tr><th>Amount</th> <td> <?php echo $case['amount']; ?> </td></tr>
    </tbody>
</table> 
<?php $i++; } ?>
<?php endif ;?>

