<br/>
<?php if( !empty($this->data['users']) ) :?>
<table id="client-details-table">    
    <tbody>
        <tr><th colspan="2" style="text-align:left">Personal Info</th></tr>
        <tr><th>Name</th> <td> <?php echo getElement( 'name', $this->data['users'] ); ?> </td></tr>
        <tr><th>Email</th> <td> <?php echo getElement( 'email', $this->data['users'] ); ?> </td></tr>
        <tr><th>Contact Person</th> <td> <?php echo getElement( 'contact_person', $this->data['users'] ); ?> </td></tr>        
        <tr><th>Contact Number</th> <td> <?php echo getElement( 'mobile_number', $this->data['users'] ); ?>,<?php echo getElement( 'home_phone', $this->data['users'] ); ?> </td></tr>
        <tr><th>Address</th> <td><?php echo getElement( 'street_line', $this->data['users'] ); ?>,<?php echo getElement( 'city', $this->data['users'] ); ?></td></tr>
        
        <tr><th colspan="2" style="text-align:left">Bank Details</th></tr>
        <tr><th>Name of the Bank</th> <td><?php echo getElement( 'bank_name', $this->data['users'] ); ?></td></tr>
        <tr><th>Account Number</th> <td><?php echo getElement( 'bank_account_number', $this->data['users'] ); ?></td></tr> 
        <tr><th>IFSC Code</th> <td><?php echo getElement( 'IFSC_code', $this->data['users'] ); ?></td></tr> 
        <tr><th>Pan Number</th> <td><?php echo getElement( 'pan_card_number', $this->data['users'] ); ?></td></tr> 
    </tbody>
</table>  
<?php endif ;?>
<br/>
