<?php echo 'hello:'. $this->data['id'] . ' ' .$this->data['name']; ?>
<table id="client-details-table">
    <tbody>
        <tr><th>Name</th> <td> Sachin </td></tr>
        <tr><th>Email</th> <td> sachin@cybage.com</td></tr>
        <tr><th>Contact Person</th> <td> anyone </td></tr>        
        <tr><th>Contact Number</th> <td> Sachin </td></tr>
        <tr><th>Address</th> <td> Sachin </td></tr>
        <tr><th>Bank Details</th> <td> Sachin </td></tr>        
    </tbody>
</table>    
<h3> Case Status </h3>
