<br/>
<?php if( !empty($this->data['case']) ) : ?>
    <div id="dataTable">
        <table cellpadding="0" cellspacing="0" border="0" class="dataTable" width="100%">
            <thead>
                <tr>
                    <?php 
                        if( App_User::get('user_type') == USER_CLIENT ) {
                            echo '<th style="width:110;"> Lawyer </th>';
                        }elseif( App_User::get('user_type') == USER_LAWYER ) {
                            echo '<th style="width:110;"> Client </th>';
                        }else {
                            echo '<th style="width:110;"> Lawyer </th><th style="width:110;"> Client </th>';
                        }                       
                    ?>
                    <th> Date of Allotment</th>
                    <th> Due Date </th>
                    <th> Closed By </th>
                    <th> Closing Date </th>
                    <th> Action</th>
                </tr>
            </thead>
            <tbody>
            <?php
                $strTable = '';
                foreach( $this->data['case'] as $arrCase) {
                    $strTable .='<tr>';
                    if( App_User::get('user_type') == USER_CLIENT ) {
                        $strTable .='<td class="action"> 
                                        <a href=# id="lawyer_' . $arrCase['lawyer_id'] . '">'
                                            . $this->userList[USER_LAWYER][$arrCase['lawyer_id']] .'</a></td>';
                    }elseif( App_User::get('user_type') == USER_LAWYER ) {
                        $strTable .='<td class="action">
                                        <a href=# id="client_' . $arrCase['client_id'] . '">'
                                            . $this->userList[USER_CLIENT][$arrCase['client_id']] .'</a></td>';
                    }else {
                        $strTable .='<td class="action">
                                        <a href=# id="lawyer_' . $arrCase['lawyer_id'] . '">'
                                            . $this->userList[USER_LAWYER][$arrCase['lawyer_id']] .'</a></td>
                                     <td class="action">
                                        <a href=# id="client_' . $arrCase['client_id'] . '">'
                                            . $this->userList[USER_CLIENT][$arrCase['client_id']] .'</a></td>';
                    }
                    
                    $strDateOfAllotment = ( false == is_null( $arrCase['date_of_allotment'] ) ) 
                                            ? date( 'm/d/Y', strtotime( $arrCase['date_of_allotment'] ) ) : '';
                    $strDueDate         = ( false == is_null( $arrCase['due_date'] ) ) 
                                            ? date( 'm/d/Y', strtotime( $arrCase['due_date'] ) ) : '';
                    $strClosingDate     = ( false == is_null( $arrCase['closing_date'] ) ) 
                                            ? date( 'm/d/Y', strtotime( $arrCase['closing_date'] ) ) : 'N/A';
                    $strClosedBy        = ( false == is_null( $arrCase['closing_date'] ) ) 
                                            ? $this->userList[USER_ADMIN][$arrCase['closed_by']] : 'N/A';

                    $strTable .='<td>' . $strDateOfAllotment . '</td>
                                 <td>' . $strDueDate . '</td>
                                 <td>' . $strClosedBy . '</td>
                                 <td>' . $strClosingDate . '</td>';

                    $strTable .='<td id="' . $arrCase['id'] .'" class="action">
                                    <a href="#" id="View">View</a> | 
                                    <a href="edit-case/id/' . $arrCase['id'] . '" id="Edit">Edit</a> | 
                                    <a href="#" id="Add Details">Add Details</a> | 
                                    <a href="#" id="Add Budget">Add Budget</a> | 
                                    <a href="#" id="Delete">Delete</a>
                                 </td></tr>';   
                }
            echo $strTable; ?>  
            </tbody>
        </table>
    </div>
<?php endif ;?>
<br/>