<br/>
<?php if( !empty( $this->data['case'] ) ) : 
        $arrCaseHistory   = $this->data['history'];
        $arrCaseBudgets   = $this->data['budget'];
        $arrCaseDocuments = $this->data['documents'];
        $arrCase          = $this->data['case'];
         ?>
    <div id="dataTable">
        <table cellpadding="0" cellspacing="0" border="0" class="dataTable" width="100%">
            <tr><th colspan="4">Case Details</th>
            <th>Closed On<?php echo $arrCase['date_of_allotment']; ?></th></tr>
            <tr>
                <th>Judge Name</th>
                <th>Hearing Date</th>
                <th>Next Alloted Hearing Date</th>
                <th></th>
                <th></th>
            </tr> 
                <?php
                    $strRows = '';
                    foreach( $arrCaseHistory as $arrMixCaseDetail ) {
                        $strResultRow = '<tr><td>' . $arrMixCaseDetail['judge_name'] . '</td>
                                         <td>' . $arrMixCaseDetail['hearing_date'] . '</td>';
                        $strOptional  = ( true == is_null( $arrCase['closed_by'] ) )
                                         ? '<td>Closed</td>' 
                                         : '<td>' . $arrMixCaseDetail['next_hearing_date'] . '</td>';
                        $strRows .= $strResultRow . $strOptional .'</tr>';
                    }
                    echo $strRows;
                ?>                 
                <td>View Detail</td>
            </tr>
            <tr><th>Case Documents</th></tr>

            <tr><th>Case Alloted Budgets</th></tr>
        </table>
    </div>
<?php endif ;?>
<br/>