<div id="content">     
    
<script type="text/javascript">
    	$(function(){
    		$('legend').click(function(){
                        //$(this).parent().find('.lawyer-form').show();
    			$(this).parent().find('.client-form').slideToggle();
    		});
    	});
                
</script>
<div id="dataTable">
  	<table cellpadding="0" cellspacing="0" border="0" class="display dataTable" id="example" width="100%">
		<thead>
			<tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile No</th>
                            <th>Address</th>    
                            <th></th>    
                        </tr>
                </thead>
                <tbody>
                    <?php foreach( $this->clientList as $client ) { ?>
                        <tr> 
                            <td><a href="#" class ="view-client" id="view_client_<?php echo $client['id']?>"><?php echo $client['name'];?></a></td>
                            <td><?php echo $client['email'];?></td>
                            <td><?php echo $client['mobile_number'];?> <?php if( $client['home_phone'] ) { echo  '/'.$client['home_phone'] ;}?> </td>
                            <td><?php echo $client['street_line'];?>,<?php echo $client['city'];?></td>
                            <td><a title="Edit Client" href="/client/edit-client/id/<?php echo $client['id'] ?>"><img src="/images/edit-icon.png" alt="Edit" height="16" width="16"> </a> &nbsp;&nbsp;
                                <a title="Delete Client" href=""> <img src="/images/delete-icon.png" alt="Delete" height="16" width="16"> </a> &nbsp;&nbsp;
                                   <a href="/client/view-client-case/id/<?php echo $client['id'] ?>"><img id = "view" src="/images/view-icon.png" alt="view" height="16" width="16"></a> </td> 
                        </tr>
                    <?php } ?>
                         
                </tbody>
           </table>                                 
</div>
<br/><br/>
<fieldset>
    <legend>Add Client</legend>    
    <div class="client-form">       
    	<?php echo $this->registerForm; ?>  
    </div>
</fieldset>
<br/>
<!--
<fieldset>
    <legend>Search Client</legend>    
    <div class="client-form">
    	<?php //echo $this->searchForm; ?>  
    </div>
</fieldset>
<br/>-->
<div><input type="hidden" id="role_type" value="3"></div>
<!--<div> 
<table id="search-table" class="display" cellpadding="0" cellspacing="0" border="0" width="100%"> 
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile No</th>
        <th>Address</th>    
        <th></th> 
    </tr>
    </thead>
    <tbody>       
        <tr id="no-record-tr"><td>No Records <td></tr>
    </tbody>
</table>
</div>-->

</div>
<div id="dialog-form-client" title="Client Details" style="display: none;"></div>