<div class="banner-strip"></div>
<div id="content">     
    
<script type="text/javascript" language="javascript">
   $(document).ready(function() {
       $( ".datepicker" ).datepicker({
         showOn: "button",
         buttonImage: "/images/calendar.gif",
         buttonImageOnly: true
       });

       $('#example').dataTable();
       /*{ we will be calling this for server side loading
           "bProcessing": true,
           "bServerSide": true,
           "sAjaxSource": "../server_side/scripts/server_processing.php"
          }*/
   });
                
</script>
<style type="text/css" media="screen">
	.dataTables_info { padding-top: 0; }
	.dataTables_paginate { padding-top: 0; }
	.css_right { float: right; }
	#example_wrapper .fg-toolbar { font-size: 0.8em }
	#theme_links span { float: left; padding: 2px 10px; }
</style>
<div id="dataTable">
  	<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
		<thead>
			<tr>
				<?php 
					if( App_User::get('user_type') == USER_CLIENT ) {
						echo '<th> Lawyer </th>';
					}elseif( App_User::get('user_type') == USER_LAWYER ) {
						echo '<th> Client </th>';
					}else {
						echo '<th> Lawyer </th><th> Client </th>';
					}						
				?>
				<th> Date of Allotment</th>
				<th> Due Date </th>
				<th> Closed By </th>
				<th> Closing Date </th>
				<th> Action</th>
			</tr>
		</thead>
		<tbody>
		<?php
		 	$strTable = '';
			foreach( $this->dataList as $arrCase) {
				$strTable .='<tr>';
				if( App_User::get('user_type') == USER_CLIENT ) {
					$strTable .='<td> <a href=#>'. $this->userList[USER_LAWYER][$arrCase['lawyer_id']] .'</a></td>';
				}elseif( App_User::get('user_type') == USER_LAWYER ) {
					$strTable .='<td> <a href=#> '. $this->userList[USER_CLIENT][$arrCase['client_id']] .'</a></td>';
				}else {
					$strTable .='<td> <a href=#> '. $this->userList[USER_LAWYER][$arrCase['lawyer_id']] .'</a></td>
								 <td> <a href=#> '. $this->userList[USER_CLIENT][$arrCase['client_id']] .'</a></td>';
				}	
				$strTable .='<td>' . date( 'm/d/Y', strtotime( $arrCase['date_of_allotment'] ) ) . '</td>
							 <td>' . date( 'm/d/Y', strtotime( $arrCase['due_date'] ) ) . '</td>
							 <td>' . date( 'm/d/Y', $arrCase['closed_by'] ) . '</td>
							 <td>' . date( 'm/d/Y', $arrCase['closing_date'] ) . '</td>
							 <td>Details | Budget | View | Edit | Delete</td></tr>';	
			}
		echo $strTable; ?>	
		</tbody>
	</table>
</div>
<?php 
   if( false == in_array( App_User::get('user_type'), array( USER_LAWYER, USER_CLIENT ) ) ) {
		echo '<fieldset>
			    	<legend>Add Case</legend>    
			    	<div class="case-form">       
		    			' . $this->registerForm . '
		    		</div>
				</fieldset>';
	}
?>  

<br/>
</div>