<div class="banner-strip"></div>
<div id="content">     

<script type="text/javascript" language="javascript">
	var case_id = null;
   $(document).ready(function() {
       $( ".datepicker" ).datepicker({
         showOn: "button",
         buttonImage: "/images/calendar.gif",
         buttonImageOnly: true,
         dateFormat: 'yy-mm-dd'
       }).attr( 'readOnly', true );

       $('#example').dataTable();
       /*{ we will be calling this for server side loading
           "bProcessing": true,
           "bServerSide": true,
           "sAjaxSource": "../server_side/scripts/server_processing.php"
          }*/
         $('td.action').on( 'click', function(){
         	case_id = this.id;
         	div_title = event.target.text;
         	switch(div_title) {
				case 'Edit':
				  break;
				case 2:
				  break;
				default:				
			}

         	$('#dialog-div p').html( case_id );
         	$('#dialog-div').dialog({
         		title: div_title + ' Case',
      			modal: true
	    	});
         });
   });
                
</script>
<style type="text/css" media="screen">
	.dataTables_info { padding-top: 0; }
	.dataTables_paginate { padding-top: 0; }
	.css_right { float: right; }
	#example_wrapper .fg-toolbar { font-size: 0.8em }
	#theme_links span { float: left; padding: 2px 10px; }
	td{text-align: center;}
</style>
<div id="dataTable">
  	<table cellpadding="0" cellspacing="0" border="0" class="display" id="example" width="100%">
		<thead>
			<tr>
				<?php 
					if( App_User::get('user_type') == USER_CLIENT ) {
						echo '<th style="width:110;"> Lawyer </th>';
					}elseif( App_User::get('user_type') == USER_LAWYER ) {
						echo '<th style="width:110;"> Client </th>';
					}else {
						echo '<th style="width:110;"> Lawyer </th><th style="width:110;"> Client </th>';
					}						
				?>
				<th> Date of Allotment</th>
				<th> Due Date </th>
				<th> Closed By </th>
				<th> Closing Date </th>
				<th> Action</th>
			</tr>
		</thead>
		<tbody>
		<?php
		 	$strTable = '';
			foreach( $this->dataList as $arrCase) {
				$strTable .='<tr>';
				if( App_User::get('user_type') == USER_CLIENT ) {
					$strTable .='<td> <a href=#>'. $this->userList[USER_LAWYER][$arrCase['lawyer_id']] .'</a></td>';
				}elseif( App_User::get('user_type') == USER_LAWYER ) {
					$strTable .='<td> <a href=#> '. $this->userList[USER_CLIENT][$arrCase['client_id']] .'</a></td>';
				}else {
					$strTable .='<td> <a href=#> '. $this->userList[USER_LAWYER][$arrCase['lawyer_id']] .'</a></td>
								 <td> <a href=#> '. $this->userList[USER_CLIENT][$arrCase['client_id']] .'</a></td>';
				}
				$strDateOfAllotment = ( false == is_null( $arrCase['date_of_allotment'] ) ) 
										? date( 'm/d/Y', strtotime( $arrCase['date_of_allotment'] ) ) : '';
				$strDueDate 		= ( false == is_null( $arrCase['due_date'] ) ) 
										? date( 'm/d/Y', strtotime( $arrCase['due_date'] ) ) : '';
				$strClosingDate 	= ( false == is_null( $arrCase['closing_date'] ) ) 
										? date( 'm/d/Y', strtotime( $arrCase['closing_date'] ) ) : 'N/A';
				$strClosedBy		= ( false == is_null( $arrCase['closing_date'] ) ) 
										? $this->userList[USER_ADMIN][$arrCase['closed_by']] : 'N/A';

				$strTable .='<td>' . $strDateOfAllotment . '</td>
							 <td>' . $strDueDate . '</td>
							 <td>' . $strClosedBy . '</td>
							 <td>' . $strClosingDate . '</td>';

				$strTable .='<td id="' . $arrCase['id'] .'" class="action">
							 	<a href="#">View</a> | 
							 	<a href="#">Edit</a> | 
							 	<a href="#">Add Details</a> | 
							 	<a href="#">Add Budget</a> | 
							 	<a href="#">Delete</a>
							 </td></tr>';	
			}
		echo $strTable; ?>	
		</tbody>
	</table>
</div>
<div id="dialog-div" title="" style="display: none;"><p></p></div>
	
<?php 
   if( true == in_array( App_User::get('user_type'), array( USER_ADMIN, USER_ADMINISTRATOR ) ) ) {
		echo '<fieldset>
			   	<legend>Add Case</legend>    
			   	<div class="case-form">       
		    		' . $this->registerForm . '
		    	</div>
			 </fieldset>';
	}
?>  
<br/>
</div>