<div id="content">     
<fieldset>
    <legend>Maharashtra</legend>    
    <div class="contact-form">       
            <table width="80%">
    <tbody>
        <tr>
            <td id="contact-title">
                <span> Mumbai </span>
            </td>
            <td id="contact-title">
                <span>Pune</span>
            </td>
        </tr>
        <tr>
            <td id="contact-text">
                C/o. Mr.Meghnath Navlani,
                35, Atlanta, 209,
                Nariman Point, Mumbai – 400 021
                Mumbai 400 021
                India
                Phone: + 91 9970341100
                E-Mail:mumbai@astrealegal.com
            </td>

            <td id="contact-text">
                Mr. Manish Modak,
                D39/38,Prasad Apartment,
                Near Maha-Bank House,
                Lane No.9, Prabhat Road
                Pune – 411004
                +91 020 65108782
                E-Mail:contact@astrealegal.com 
            </td>
        </tr>
        <tr>
            <td id="contact-title">
                <span> Nagpur </span>
            </td>
            <td id="contact-title">
                <span>Amravati</span>
            </td>
        </tr>                                                        
        <tr>  
            <td id="contact-text">
                Mr.Ashish Bang,
                464-A, Professor Colony,
                Hanuman Nagar, 44009
                +919422829833
                E-Mail:contact@astrealegal.com
            </td>
            <td id="contact-text">
                Mr. Manish Modak,
                3rd Lane, Narayan Nagar,
                444603
                +91 9970341100
                E-Mail:contact@astrealegal.com    
            </td>
        </tr>
    </tbody>     
</table>

    </div>
</fieldset>
    <br/>
  <fieldset>
    <legend>AndhraPradesh</legend>    
    <div class="contact-form">       
            <table width="80%">
    <tbody>
        <tr>
            <td id="contact-title">
                <span> Hyderabad </span>
            </td>
          
        </tr>
        <tr>
            <td id="contact-text">
                Mrs.Neelam Narania,
                2-1-327/8/8/1/3, First Floor,
                Vegetable Market Road, Nallakunta,
                Opposite Windsor Plaza,
                Hyderabad -44,Andhra Pradesh

                E-Mail:hyd@astrealegal.com 
            </td>
        </tr>
      </tbody>     
</table>

    </div>
</fieldset>
  
    
<br/>
</div>


